; ---- a metacircular Lisp evaluator, written in Lisp ----
(define (meval exp env)
  (cond ((number? exp) exp)
        ((symbol? exp) (cdr (assoc exp env)))
        ((eq? (car exp) (quote quote)) (cadr exp))
        ((eq? (car exp) (quote if))
         (if (meval (cadr exp) env) (meval (caddr exp) env) (meval (cadddr exp) env)))
        ((eq? (car exp) (quote lambda))
         (list (quote closure) (cadr exp) (caddr exp) env))
        (else (mapply (meval (car exp) env)
                      (map (lambda (a) (meval a env)) (cdr exp))))))
(define (mapply fn args)
  (cond ((eq? (car fn) (quote closure))
         (meval (caddr fn) (bind (cadr fn) args (cadddr fn))))
        (else (apply fn args))))
(define (bind params args env)
  (if (null? params) env
      (cons (cons (car params) (car args)) (bind (cdr params) (cdr args) env))))
(define genv (list (cons (quote +) +) (cons (quote *) *) (cons (quote -) -)
                   (cons (quote car) car) (cons (quote cdr) cdr) (cons (quote cons) cons)
                   (cons (quote eq?) eq?) (cons (quote <) <) (cons (quote null?) null?)))
(print (meval (quote ((lambda (x) (* x x)) 5)) genv))
(print (meval (quote (if (eq? 1 1) (quote yes) (quote no))) genv))
(print (meval (quote ((lambda (x) (cons x (cons x (quote ())))) 7)) genv))
(print (meval (quote (+ 3 (* 4 5))) genv))
; recursion with NO define -- the Y combinator, evaluated by the metacircular evaluator
(define facty
  (quote ((lambda (f) ((lambda (x) (f (lambda (v) ((x x) v))))
                       (lambda (x) (f (lambda (v) ((x x) v))))))
          (lambda (self) (lambda (n) (if (< n 2) 1 (* n (self (- n 1)))))))))
(print (meval (list facty 6) genv))
