(define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
(print (fact 10))
(define (fib n) (if (< n 2) n (+ (fib (- n 1)) (fib (- n 2)))))
(print (fib 15))
(print (map (lambda (x) (* x x)) (list 1 2 3 4 5)))
(print (append (list 1 2) (list 3 4)))
(print (reverse (list 1 2 3)))
(define (make-adder n) (lambda (x) (+ x n)))
(define add5 (make-adder 5))
(print (add5 10))
(print (assoc (quote b) (list (list (quote a) 1) (list (quote b) 2))))
(let ((x 3) (y 4)) (print (+ x y)))
(print (filter (lambda (x) (> x 2)) (list 1 2 3 4 5)))
