<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ilshell</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\..\icons\ilforge.ico</ApplicationIcon>
    <Product>ILForge</Product>
    <AssemblyTitle>ILForge Shell</AssemblyTitle>
  </PropertyGroup>
</Project>
