; ilforge.iss - Inno Setup script for ILForge (Setup.exe + uninstaller).
;
; Build the payload first, then compile with Inno Setup's ISCC:
;     powershell -File installer\build_dist.ps1
;     ISCC installer\ilforge.iss           (needs Inno Setup: https://jrsoftware.org/isdl.php)
;
; Produces installer\Output\ILForge-setup.exe: a per-machine install into
; Program Files with an Add/Remove-Programs entry, an ILForge Start Menu group
; (windowed shell, console shell, developer command prompt, documentation), and
; the brand icon on every shortcut.

#define AppName    "ILForge"
#define AppVer     "1.0"
#define AppTag     "ILForge - Polyglot .NET Compiler Workbench"

[Setup]
AppId={{7F3C1E90-4B22-4E4E-9E1A-ILFORGE00001}
AppName={#AppName}
AppVersion={#AppVer}
AppVerName={#AppTag}
AppPublisher=ILForge
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
PrivilegesRequired=admin
Compression=lzma2
SolidCompression=yes
OutputDir=Output
OutputBaseFilename=ILForge-setup
SetupIconFile=..\icons\ilforge.ico
UninstallDisplayIcon={app}\icons\ilforge.ico
UninstallDisplayName={#AppTag}
ArchitecturesInstallIn64BitMode=x64compatible

[Files]
; the toolchain (the seed home is handled below; it must not land in Program Files)
Source: "..\dist\ILForge\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion; \
    Excludes: "install.ps1,uninstall.ps1,home\*,home"
; seed the user's home once, outside the install tree, never overwriting their copy
Source: "..\dist\ILForge\home\*"; DestDir: "{localappdata}\ILForge\home"; \
    Flags: recursesubdirs createallsubdirs onlyifdoesntexist uninsneveruninstall

[Icons]
Name: "{group}\ILForge Shell"; Filename: "{app}\src\ilterm\bin\Release\net10.0\ilterm.exe"; \
    Parameters: """{app}\out\ilsh.dll"" --home ""{localappdata}\ILForge\home"""; \
    WorkingDir: "{localappdata}\ILForge\home"; IconFilename: "{app}\icons\ilforge.ico"; \
    Comment: "ILForge Shell - windowed terminal (color, fonts, menu)"
Name: "{group}\ILForge Shell (console)"; Filename: "{app}\src\ilshell\bin\Release\net10.0\ilshell.exe"; \
    Parameters: """{app}\out\ilsh.dll"" --home ""{localappdata}\ILForge\home"""; \
    WorkingDir: "{localappdata}\ILForge\home"; IconFilename: "{app}\icons\ilforge.ico"; \
    Comment: "ILForge Shell in a console window"
Name: "{group}\ILForge Developer Command Prompt"; Filename: "{cmd}"; \
    Parameters: "/k ""{app}\ilforge-cmd.bat"" ""{localappdata}\ILForge\home"""; WorkingDir: "{localappdata}\ILForge\home"; \
    IconFilename: "{app}\icons\ilforge.ico"; \
    Comment: "Windows console with the whole ILForge toolchain on PATH"
Name: "{group}\ILForge Documentation"; Filename: "{app}\docs"; \
    IconFilename: "{app}\icons\ilforge.ico"; Comment: "Language and toolchain documentation"
Name: "{group}\Uninstall ILForge"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\src\ilterm\bin\Release\net10.0\ilterm.exe"; \
    Parameters: """{app}\out\ilsh.dll"" --home ""{localappdata}\ILForge\home"""; \
    WorkingDir: "{localappdata}\ILForge\home"; Description: "Launch ILForge Shell now"; \
    Flags: nowait postinstall skipifsilent

[Code]
// write home\.ilshellrc with the installed layout, only if it does not already exist
procedure CurStepChanged(CurStep: TSetupStep);
var rc, app, home, prof, s: String;
begin
  if CurStep = ssPostInstall then begin
    app  := ExpandConstant('{app}');
    home := ExpandConstant('{localappdata}\ILForge\home');
    rc   := home + '\.ilshellrc';
    if not FileExists(rc) then begin
      prof := GetEnv('USERPROFILE');
      // values are quoted: an install path may contain a space (C:\Program Files\...) and
      // the shell splits an unquoted assignment at whitespace, exactly as sh does.
      s := '# ILForge shell startup, generated by the installer (run ''refresh'' to reload).'#13#10
         + 'home=''' + home + ''''#13#10
         + 'bin=''' + app + '\out'''#13#10
         + 'lib=''' + app + '\out'''#13#10
         + 'include=''' + app + '\include'''#13#10
         + 'etc=''' + app + '\etc'''#13#10
         + 'tmp=''' + app + '\tmp'''#13#10
         + 'windows=''' + prof + ''''#13#10
         + 'alias ll=''ls -al'''#13#10
         + 'echo "ILForge ready.  ''vfs status'' shows the layout; ''refresh'' reloads this file."'#13#10;
      SaveStringToFile(rc, s, False);
    end;
  end;
end;
