# install.ps1 — install the dotnetcompilers toolchain for the current user and put the
# shell on the Start Menu.  Run this from inside the unzipped package:
#
#   powershell -ExecutionPolicy Bypass -File install.ps1 [-Dest <dir>] [-HomeDir <dir>]
#
#   -Dest      where the toolchain is installed (default %LOCALAPPDATA%\Programs\ildev)
#   -HomeDir   the shell's home directory (default <Dest>\home). May be any path; it
#              persists independently of the install and is never overwritten.

param(
    [string]$Dest = "$env:LOCALAPPDATA\Programs\ildev",
    [string]$HomeDir = ""
)
$ErrorActionPreference = "Stop"
$src = $PSScriptRoot
if (-not $HomeDir) { $HomeDir = Join-Path $Dest "home" }

# .NET 10 runtime is required to run the toolchain (SDK only needed to compile new exes).
$rt = & dotnet --list-runtimes 2>$null
if (-not ($rt -match "Microsoft\.NETCore\.App 10\.")) {
    Write-Warning "The .NET 10 runtime was not detected."
    Write-Warning "Install it from https://dotnet.microsoft.com/download/dotnet/10.0 (the toolchain needs it to run)."
}

Write-Host "Installing to $Dest ..."
New-Item -ItemType Directory -Force $Dest | Out-Null
# copy everything except the installer scripts and the home directory (home persists across
# reinstalls, so it's never overwritten -- it's seeded separately, only when absent).
Get-ChildItem $src -Force | Where-Object { $_.Name -notin @("install.ps1", "uninstall.ps1", "home") } |
    ForEach-Object { Copy-Item $_.FullName -Destination $Dest -Recurse -Force }

# ----- persistent home directory (may live anywhere; never overwritten) -----
if (-not (Test-Path $HomeDir)) { New-Item -ItemType Directory -Force $HomeDir | Out-Null; Write-Host "Created home directory: $HomeDir" }
else { Write-Host "Using existing home directory: $HomeDir" }
# seed default files (.quicklaunch etc.) only where they're missing -- never clobber the user's
if (Test-Path (Join-Path $src "home")) {
    Get-ChildItem (Join-Path $src "home") -Force | ForEach-Object {
        $t = Join-Path $HomeDir $_.Name
        if (-not (Test-Path $t)) { Copy-Item $_.FullName $t -Recurse -Force; Write-Host "Seeded $($_.Name)" }
    }
}

# generate .ilshellrc with the installed directory layout, but only if it doesn't exist yet
# (so the user's edits persist across reinstalls).
$rc = Join-Path $HomeDir ".ilshellrc"
if (-not (Test-Path $rc)) {
    $profile = [Environment]::GetFolderPath("UserProfile")
    @"
# IL Shell startup script, generated by the installer.
# Edit freely -- this file persists across reinstalls. Run 'refresh' to reload it.
# The Start Menu shortcut already enabled the virtual filesystem (--home), so the tree
# is live; these lines set the mounts to the installed layout (override as you like).

home=$homeDir
bin=$Dest\out
lib=$Dest\out
include=$Dest\include
etc=$Dest\etc
tmp=$Dest\tmp
windows=$profile

alias ll='ls -al'
alias la='ls -a'
echo "IL Shell ready.  'vfs status' shows the layout; 'refresh' reloads this file."
"@ | Set-Content -Path $rc -Encoding ASCII
    Write-Host "Wrote $rc"
}
else {
    # A kept .ilshellrc may have been written for a different install location (e.g. the
    # toolchain was reinstalled elsewhere). Rebase the install-relative mount lines
    # (bin/lib/include/etc/tmp) to this install dir, preserving home (independent), aliases,
    # and every other edit. The old install dir is read from the bin= line. No-op if matched.
    $lines = @(Get-Content $rc)
    $oldInstall = $null
    foreach ($l in $lines) { if ($l -match '^\s*bin\s*=\s*(.+?)\s*$') { $oldInstall = (Split-Path $matches[1] -Parent); break } }
    if ($oldInstall) {
        $oldp = $oldInstall.TrimEnd('\'); $newp = $Dest.TrimEnd('\')
        if (-not $oldp.Equals($newp, [System.StringComparison]::OrdinalIgnoreCase)) {
            $changed = $false
            for ($i = 0; $i -lt $lines.Count; $i++) {
                if ($lines[$i] -match '^\s*(bin|lib|include|etc|tmp)\s*=\s*(.+?)\s*$') {
                    $key = $matches[1]; $val = $matches[2]
                    if ($val.StartsWith($oldp, [System.StringComparison]::OrdinalIgnoreCase)) {
                        $lines[$i] = "$key=$newp" + $val.Substring($oldp.Length); $changed = $true
                    }
                }
            }
            if ($changed) {
                Set-Content -Path $rc -Value $lines -Encoding ASCII
                Write-Host "Rebased .ilshellrc mount paths ($oldInstall -> $Dest); your aliases were kept."
            }
        }
    }
}

$ilterm = Join-Path $Dest "src\ilterm\bin\Release\net10.0\ilterm.exe"
$ilshDll = Join-Path $Dest "out\ilsh.dll"
$ilshell = Join-Path $Dest "src\ilshell\bin\Release\net10.0\ilshell.exe"
if (-not (Test-Path $ilterm))  { throw "ilterm.exe missing in package ($ilterm) - was the package built fully?" }
if (-not (Test-Path $ilshDll)) { throw "out\ilsh.dll missing in package" }

$programs = [Environment]::GetFolderPath("Programs")          # per-user Start Menu\Programs
$ws = New-Object -ComObject WScript.Shell

# the shortcut launches in the persistent home directory (virtual filesystem on)
$homeArg = '"' + $ilshDll + '" --home "' + $homeDir + '"'

# primary: the windowed terminal (color, fonts, right-click menu)
$lnk = $ws.CreateShortcut((Join-Path $programs "IL Shell.lnk"))
$lnk.TargetPath = $ilterm
$lnk.Arguments = $homeArg
$lnk.WorkingDirectory = $Dest
$lnk.Description = "IL Shell - the dotnetcompilers toolchain (windowed terminal)"
$lnk.Save()

# secondary: the plain console shell
if (Test-Path $ilshell) {
    $lnk2 = $ws.CreateShortcut((Join-Path $programs "IL Shell (console).lnk"))
    $lnk2.TargetPath = $ilshell
    $lnk2.Arguments = $homeArg
    $lnk2.WorkingDirectory = $Dest
    $lnk2.Description = "IL Shell in a console window"
    $lnk2.Save()
}

Write-Host ""
Write-Host "Installed to:        $Dest"
Write-Host "Start Menu shortcut: $(Join-Path $programs 'IL Shell.lnk')"
Write-Host "Search the Start Menu for 'IL Shell' to launch it."
